# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-02 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190902_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='pulisher',
            new_name='publisher',
        ),
    ]
