# Generated by Django 2.2 on 2020-03-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20190902_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
